import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: require("../assets/1.png"),
    title: "Simple Kitchen FD Sliced Strawberries – 1.08lb",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    discount: "75%",
    color: "green",
    category: "Beverages",
    status: "In Stock",
    discount: "15%",
    brand: "Fresh",
    description: "Strawberry powder is a dehydrated and finely ground form of strawberries. It is a versatile ingredient used in various culinary and cosmetic applications due to its concentrated flavor, color, and nutritional benefits. Here are some key points about strawberry powder",
    reviews: "They have a sunny sweetness that always reminds us of the start of summer. Not only are they great for snacking on as dried chips, but they can be used for a lot of different culinary applications. Dehydrated strawberries can be used to top oatmeal, cereal, or yogurt. They can be baked into scones or muffins",
  },
  {
    id: 2,
    img: require("../assets/7.png"),
    title: "Yellow Potatoes Whole Fresh, 5lb Bag",
    star: <AiFillStar className="rating-star" />,
    rating: "(13 reviews)",
    prevPrice: "$500,00",
    newPrice: "150",
    discount: "75%",
    color: "green",
    category: "Vegetables",
    status: "Sold Out",
    brand: "King",
    description: "potato Yellow potatoes, also known as Yukon Gold or yellow-fleshed potatoes, are a popular variety of potatoes that are valued for their creamy texture, buttery flavor, and versatility in cooking.",
    reviews: " Yellow potatoes are relatively low in calories, making them a healthy addition to meals when prepared without excessive fats.When stored properly, yellow potatoes can last for several weeks.",
  },

  {
    id: 3,
    img: require("../assets/2.png"),
    title: "Blackberries – 6oz",
    star: <AiFillStar className="rating-star" />,
    rating: "(140 reviews)",
    prevPrice: "$100,00",
    newPrice: "100",
    discount: "25%",
    color: "green",
    category: "Fruits",
    status: "In Stock",
    brand: "Fresh",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },
  {
    id: 4,
    img: require("../assets/3.png"),
    title: "Large Bagged Oranges",
    star: <AiFillStar className="rating-star" />,
    rating: "(14 reviews)",
    prevPrice: "$120,00",
    newPrice: "100",
    discount: "58%",
    color: "green",
    category: "Fruits",
    status: "In Stock",
    brand: "Fresh",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },
  {
    id: 5,
    img: require("../assets/9.png"),
    title: "Fresh Cauliflower, Each",
    star: <AiFillStar className="rating-star" />,
    rating: "(33 reviews)",
    prevPrice: "$140,00",
    newPrice: "600",
    discount: "63%",
    color: "green",
    category: "Vegetables",
    status: "In Stock",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },
  {
    id: 6,
    img: require("../assets/12.png"),
    title: "Fresh Pomegranate, Each",
    star: <AiFillStar className="rating-star" />,
    rating: "(32 reviews)",
    prevPrice: "$140,00",
    newPrice: "300",
    discount: "15%",
    color: "red",
    category: "Fruits",
    status: "In Stock",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },

  {
    id: 7,
    img: require("../assets/14.png"),
    title: "Halloween Harvest Caramel Apple Soft Caramels ",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "140",
    discount: "15%",
    color: "red",
    category: "Snacks",
    status: "Sold Out",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },

  {
    id: 8,
    img: require("../assets/5.png"),
    title: "30g Protein Shake – Salted Caramel – 11 fl oz-4pk",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$146,00",
    newPrice: "90",
    discount: "75%",
    color: "green",
    category: "Snacks",
    status: "Sold Out",
    brand: "King",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
  },

  {
    id: 9,
    img: require("../assets/13.png"),
    title: "Fresh Purple Eggplant",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    discount: "38%",
    color: "Red",
    category: "Vegetables",
    status: "Sold Out",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    brand: "Everest"
  },

  {
    id: 10,
    img: require("../assets/10.png"),
    title: "Fresh Granny Smith Apple,Each",
    star: <AiFillStar className="rating-star" />,
    rating: "(8 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    discount: "5%",
    color: "green",
    category: "Fruits",
    status: "Sold Out",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    brand: "King"
  },
  {
    id: 11,
    img: require("../assets/11.png"),
    title: "Fresh Lemon, Eac",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "450",
    discount: "10%",
    color: "red",
    category: "Fruits",
    status: "Sold Out",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    brand: "Everest"
  },
  {
    id: 12,
    img: require("../assets/8.png"),
    title: "Fresh Broccoli Crowns, Each",
    star: <AiFillStar className="rating-star" />,
    rating: "(65 reviews)",
    prevPrice: "$140,00",
    newPrice: "365",
    discount: "5%",
    color: "red",
    category: "Vegetables",
    status: "In Stock",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    brand: "Everest"
  },
  {
    id: 13,
    img: require("../assets/16.png"),
    title: "Peach – each",
    star: <AiFillStar className="rating-star" />,
    rating: "(35 reviews)",
    prevPrice: "$140,00",
    newPrice: "365",
    discount: "5%",
    color: "Red",
    category: "Beverages",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    status: "Sold Out",
    brand: "King"
  },
  {
    id: 14,
    img: require("../assets/15.png"),
    title: "Large Garden Spinach & Herb Wrap Tortillas ",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$365,00",
    discount: "5%",
    color: "Red",
    category: "Beverages",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    status: "Sold Out",
    brand: "King"
  },

  {
    id: 15,
    img: require("../assets/6.png"),
    title: "Strawberries – 1lb",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "10",
    discount: "5%",
    color: "green",
    category: "Fruits",
    status: "Sold Out",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    brand: "King"
  },
  {
    id: 16,
    img: require("../assets/4.png"),
    title: "Marketside Fresh Organic Bananas, Bunch",
    star: <AiFillStar className="rating-star" />,
    rating: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "60",
    discount: "23%",
    color: "green",
    category: "Fruits",
    description: "Blueberries are small, round, and typically blue or purple berries that are packed with nutrients and antioxidants. They are widely enjoyed for their sweet and slightly tart flavor and are used in a variety of culinary dishes. Here's more information about blueberries:.Blueberries are delicious little berries that are often found in muffins, pancakes, smoothies, and more. They're known for their sweet-tart flavor and vibrant blue color. They're also packed with antioxidants and are considered a superfood",
    reviews: "Vitamins and Minerals: Blueberries are rich in vitamin C, vitamin K, and manganese.Antioxidants: They contain high levels of antioxidants, particularly anthocyanins, which give blueberries their color and have numerous health benefits.Dietary Fiber: Blueberries provide a good amount of dietary fiber, which is beneficial for digestive health.",
    status: "In Stock",
  },
];


export default data;
